//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string SellerId { get; set; }
        public string ProductURL { get; set; }
        public string Title { get; set; }
        public string soldarray { get; set; }
        public Nullable<int> Last_Day_Sold_Number { get; set; }
        public Nullable<int> Last_7_Days_Sold { get; set; }
        public Nullable<int> Last_30_Days_Sold { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> repeatProductSold { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
