//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.Product = new HashSet<Product>();
            this.Users = new HashSet<Users>();
        }
    
        public string SellerId { get; set; }
        public Nullable<int> Rating { get; set; }
        public int Spy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> TotalSoldsInLastMonth { get; set; }
        public Nullable<int> TotalSoldsInLast7Days { get; set; }
        public Nullable<int> TotalSoldsInLast1Days { get; set; }
        public Nullable<bool> BlackList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
